apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-node
  labels:
    name: hello 
spec:
  replicas: 1
  selector:
    app: hello
    framework: node
  template:
    metadata:
      labels:
        app: hello
        framework: node
    spec:
      containers:
        - name: hello
          image: hello-node:1.2
          ports:
            - containerPort: 8080
