apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-django
  labels:
    name: hello 
spec:
  replicas: 1
  selector:
    app: hello
    framework: django
  template:
    metadata:
      labels:
        app: hello
        framework: django
    spec:
      containers:
        - name: hello
          image: hello-django:1.2
          ports:
            - containerPort: 8080
